# yaml-language-server: $schema=https://json-schema.org/draft/2020-12/schema

$schema: https://json-schema.org/draft/2020-12/schema
$id: https://example.com/coordinate.schema.yaml
description: This is a schema for a coordinate on Earth.
type: object
properties:
  latitude:
    type: number
    minimum: -90
    maximum: 90
  longitude:
    type: number
    minimum: -180
    maximum: 180